# Generated by Django 2.2 on 2021-05-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection', models.CharField(max_length=100)),
                ('dimension', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cofextension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('acohnongdu', models.FloatField(null=True)),
                ('acohliang', models.FloatField(null=True)),
                ('cas1', models.CharField(max_length=100, null=True)),
                ('cas1liang', models.FloatField(null=True)),
                ('cas2', models.CharField(max_length=100, null=True)),
                ('cas2liang', models.FloatField(null=True)),
                ('temperature', models.FloatField()),
                ('time', models.IntegerField()),
                ('is_solid', models.BooleanField()),
                ('is_crystal', models.BooleanField()),
                ('pxrd', models.IntegerField()),
                ('ssnmr', models.FloatField(null=True)),
                ('hp129', models.FloatField(null=True)),
                ('fengguan129', models.FloatField(null=True)),
                ('kongjing', models.FloatField(null=True)),
                ('bet', models.FloatField(null=True)),
                ('graph', models.CharField(max_length=254, null=True)),
                ('cif', models.CharField(max_length=254, null=True)),
                ('graphpxrd', models.CharField(max_length=254, null=True)),
                ('other', models.CharField(max_length=254)),
                ('remark', models.CharField(max_length=254)),
                ('cof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cof')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rongjiml', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cofextension')),
            ],
        ),
        migrations.CreateModel(
            name='Danti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danti', models.FloatField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('structure', models.CharField(max_length=254, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cofextension')),
            ],
        ),
        migrations.AddField(
            model_name='cof',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
        ),
    ]
