# Generated by Django 2.2 on 2021-05-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210518_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofextension',
            name='cas1',
        ),
        migrations.RemoveField(
            model_name='cofextension',
            name='cas1liang',
        ),
        migrations.RemoveField(
            model_name='cofextension',
            name='cas2',
        ),
        migrations.RemoveField(
            model_name='cofextension',
            name='cas2liang',
        ),
        migrations.CreateModel(
            name='Cuihuaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas1', models.CharField(max_length=100, null=True)),
                ('cas1liang', models.FloatField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cofextension')),
            ],
        ),
    ]
